pipelines:
  branches:
    development:
      - step:
          name: Build And Deploy
          image: node:16.18.1
          script:
            - pipe: atlassian/ssh-run:0.4.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER
                COMMAND: 'cd public_html/demo.treasuredeal.com/laravel-with-react && GIT_SSH_COMMAND="ssh -i  /home/treasuredeal1/.ssh/id_bitbucket" git pull && npm install && npm run build && pm2 restart all'